-- SQL Migration for A.V.V.M. Sri Pushpam College ERP (Supabase)
-- Instructions: Copy and paste this into the Supabase SQL Editor (https://supabase.com/dashboard/project/YOUR_PROJECT_ID/sql)

-- 1. Create Profiles (Core user table linked to Supabase Auth)
CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL PRIMARY KEY,
  full_name text NOT NULL,
  email text NOT NULL UNIQUE,
  role text CHECK (role IN ('admin', 'staff', 'student')) NOT NULL DEFAULT 'student',
  department text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now()
);

-- 2. Create Students Master Table
CREATE TABLE IF NOT EXISTS public.students (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  profile_id uuid REFERENCES public.profiles(id), -- Nullable for pre-registered students
  full_name text NOT NULL,
  register_no text UNIQUE NOT NULL,
  department text NOT NULL,
  current_year integer NOT NULL DEFAULT 1,
  current_semester integer NOT NULL DEFAULT 1,
  admission_date date DEFAULT current_date,
  status text CHECK (status IN ('active', 'inactive', 'graduated')) DEFAULT 'active'
);

-- 3. Attendance Registry
CREATE TABLE IF NOT EXISTS public.attendance (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id uuid REFERENCES public.students(id) ON DELETE CASCADE NOT NULL,
  date date DEFAULT current_date NOT NULL,
  status text CHECK (status IN ('present', 'absent', 'on-leave')) NOT NULL,
  marked_by uuid REFERENCES public.profiles(id),
  session_type text CHECK (session_type IN ('morning', 'afternoon')) DEFAULT 'morning',
  created_at timestamp with time zone DEFAULT now()
);

-- 4. Fee Management Table
CREATE TABLE IF NOT EXISTS public.fees (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id uuid REFERENCES public.students(id) ON DELETE CASCADE NOT NULL,
  fee_category text NOT NULL, -- e.g., Tuition, Hostel, Exam
  amount_due numeric(12,2) NOT NULL,
  amount_paid numeric(12,2) DEFAULT 0,
  due_date date,
  payment_status text CHECK (payment_status IN ('pending', 'partial', 'paid', 'overdue')) DEFAULT 'pending',
  transaction_ref text,
  last_payment_date timestamp with time zone
);

-- 5. Examination & Academic Results
CREATE TABLE IF NOT EXISTS public.academic_results (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id uuid REFERENCES public.students(id) ON DELETE CASCADE NOT NULL,
  subject_code text NOT NULL,
  subject_name text NOT NULL,
  internal_marks integer DEFAULT 0,
  external_marks integer DEFAULT 0,
  total_marks integer GENERATED ALWAYS AS (internal_marks + external_marks) STORED,
  grade text,
  result_status text CHECK (result_status IN ('pass', 'fail', 'withheld', 'absent')),
  semester integer NOT NULL,
  exam_date date
);

-- Enable RLS for Security
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fees ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.academic_results ENABLE ROW LEVEL SECURITY;

-- Security Policies (Row Level Security)

-- Profiles: Users see only their profile; Admin sees all
CREATE POLICY "Users can view own profile." ON public.profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Admin can view all profiles." ON public.profiles FOR ALL USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
);

-- Results: Students see only their own results
CREATE POLICY "Students view own results." ON public.academic_results FOR SELECT USING (
  EXISTS (SELECT 1 FROM public.students WHERE id = academic_results.student_id AND profile_id = auth.uid())
);

-- Staff: Can mark attendance and results for their departments
-- (Expandable later)

-- Allow new users (including admins admitting students) to insert profiles
CREATE POLICY "Enable insert for authenticated users only" ON public.profiles FOR INSERT TO authenticated WITH CHECK (true);

-- Allow admins to insert students
CREATE POLICY "Enable insert for students" ON public.students FOR INSERT TO authenticated WITH CHECK (true);

-- 6. Staff Directory
CREATE TABLE IF NOT EXISTS public.staff (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  profile_id uuid REFERENCES public.profiles(id),
  full_name text NOT NULL,
  employee_id text UNIQUE NOT NULL,
  designation text NOT NULL,
  department text NOT NULL,
  join_date date DEFAULT current_date,
  status text CHECK (status IN ('active', 'inactive', 'retired')) DEFAULT 'active'
);

-- 7. Departments Registry
CREATE TABLE IF NOT EXISTS public.departments (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  name text UNIQUE NOT NULL,
  code text UNIQUE NOT NULL,
  head_of_department uuid REFERENCES public.staff(id),
  established_year integer,
  type text CHECK (type IN ('academic', 'administrative')) DEFAULT 'academic'
);

-- 8. Events Calendar
CREATE TABLE IF NOT EXISTS public.events (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  title text NOT NULL,
  description text,
  event_date date NOT NULL,
  category text CHECK (category IN ('academic', 'cultural', 'sports', 'examination', 'placement')),
  target_audience text DEFAULT 'all',
  created_by uuid REFERENCES public.profiles(id)
);

-- 9. Library Management System
CREATE TABLE IF NOT EXISTS public.library (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  book_title text NOT NULL,
  author text NOT NULL,
  isbn text UNIQUE,
  category text,
  total_copies integer DEFAULT 1,
  available_copies integer DEFAULT 1,
  added_date date DEFAULT current_date
);

-- 10. Placements Cell
CREATE TABLE IF NOT EXISTS public.placements (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  company_name text NOT NULL,
  drive_date date NOT NULL,
  job_roles text[],
  eligible_departments text[],
  ctc_offered numeric(10,2),
  status text CHECK (status IN ('upcoming', 'completed', 'cancelled')) DEFAULT 'upcoming'
);
